// ============================================
// EduBridge AI – Explain Service
// ============================================

import { chatCompletion, DEMO_MODE } from "./openai-client";
import { generateCacheKey, getCachedResponse, setCachedResponse } from "./cache";
import { ExplainInput } from "@/lib/validations";

function getDemoExplanation(input: ExplainInput): string {
  const topic = input.topic;
  const subject = input.subject || "General";
  const difficulty = input.difficulty || "BEGINNER";

  const difficultyLabel =
    difficulty === "ADVANCED" ? "advanced" : difficulty === "INTERMEDIATE" ? "intermediate" : "beginner";

  return `# ${topic}

## Definition
**${topic}** is a fundamental concept in **${subject}** that describes how specific processes or principles operate in the natural or applied world. Understanding ${topic} is essential for building a strong foundation in ${subject}.

## Key Concepts

- **Core Principle**: ${topic} involves a systematic process that can be observed, measured, and analyzed through scientific or analytical methods.
- **Real-World Relevance**: This concept appears in everyday life — from technology and nature to industry and research.
- **Building Blocks**: To fully understand ${topic}, one must grasp the underlying components and how they interact with each other.
- **Applications**: ${topic} has practical applications across multiple fields including engineering, medicine, environmental science, and technology.
- **Historical Context**: The study of ${topic} has evolved over centuries, with key breakthroughs that changed our understanding of ${subject}.

## Real-World Analogy
Think of ${topic} like a recipe in a kitchen 🍳. Just as a recipe combines specific ingredients in a particular order to create a dish, ${topic} combines fundamental elements following specific rules to produce observable results. If you change one ingredient, the whole outcome changes — and that's exactly how ${topic} works!

## Simple Example
Imagine you're a ${difficultyLabel}-level student studying ${subject}. Here's a concrete example:

> If you observe ${topic} in action — say, in a classroom lab or in nature — you'll notice that certain inputs lead to predictable outputs. For instance, adjusting one variable while keeping others constant demonstrates the core principle at work.

## Common Misconceptions
1. **"${topic} is too complex to understand"** — While advanced aspects exist, the fundamentals are accessible at every level.
2. **"${topic} only applies in textbooks"** — In reality, ${topic} has applications all around us, from smartphones to ecosystems.
3. **"There's only one way to approach ${topic}"** — Multiple valid perspectives and methods exist for studying this concept.

---
*Explanation generated by EduBridge AI • Difficulty: ${difficultyLabel} • Subject: ${subject}*`;
}

export async function explainTopic(input: ExplainInput): Promise<string> {
  // Return demo response when OpenAI is not configured
  if (DEMO_MODE) {
    return getDemoExplanation(input);
  }

  try {
    const cacheKey = generateCacheKey("explain", input as Record<string, unknown>);
    const cached = await getCachedResponse(cacheKey);
    if (cached) return cached;

    const difficultyMap = {
      BEGINNER: "a 10-year-old child",
      INTERMEDIATE: "a high school student",
      ADVANCED: "a university student",
    };

    const audience = input.simplify
      ? "a 10-year-old child"
      : difficultyMap[input.difficulty || "BEGINNER"];

    const languageInstruction =
      input.language && input.language !== "en"
        ? `Respond entirely in the language with code "${input.language}".`
        : "";

    const systemPrompt = `You are EduBridge AI, an expert educational tutor. 
Your role is to explain concepts clearly, accurately, and engagingly.
Always use analogies and real-world examples.
Structure your response with clear headings and bullet points.
${languageInstruction}`;

    const userPrompt = `Explain the following topic as if you are teaching ${audience}:

Topic: ${input.topic}
${input.subject ? `Subject: ${input.subject}` : ""}

Provide:
1. A clear definition
2. Key concepts (3-5 points)
3. A real-world analogy
4. A simple example
5. Common misconceptions (if any)`;

    const response = await chatCompletion(
      [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      { temperature: 0.6, maxTokens: 1500 }
    );

    await setCachedResponse(cacheKey, response, "explain");
    return response;
  } catch {
    // Fallback to demo if OpenAI call fails (quota exceeded, network, etc.)
    return getDemoExplanation(input);
  }
}
