// ============================================
// EduBridge AI – Translation Service
// ============================================

import { chatCompletion, DEMO_MODE } from "./openai-client";
import { generateCacheKey, getCachedResponse, setCachedResponse } from "./cache";
import { TranslateInput } from "@/lib/validations";

const LANGUAGE_NAMES: Record<string, string> = {
  en: "English",
  hi: "Hindi",
  te: "Telugu",
  ta: "Tamil",
  kn: "Kannada",
  ml: "Malayalam",
  mr: "Marathi",
  bn: "Bengali",
  gu: "Gujarati",
  pa: "Punjabi",
  ur: "Urdu",
  es: "Spanish",
  fr: "French",
  de: "German",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  ar: "Arabic",
  pt: "Portuguese",
  ru: "Russian",
};

const DEMO_TRANSLATIONS: Record<string, Record<string, string>> = {
  hi: {
    greeting: "यह एक डेमो अनुवाद है।",
    prefix: "📝 हिन्दी अनुवाद (डेमो):\n\n",
    note: "\n\n---\n*यह EduBridge AI द्वारा उत्पन्न एक डेमो अनुवाद है।*",
  },
  te: {
    greeting: "ఇది ఒక డెమో అనువాదం.",
    prefix: "📝 తెలుగు అనువాదం (డెమో):\n\n",
    note: "\n\n---\n*ఇది EduBridge AI ద్వారా రూపొందించబడిన డెమో అనువాదం.*",
  },
  ta: {
    greeting: "இது ஒரு டெமோ மொழிபெயர்ப்பு.",
    prefix: "📝 தமிழ் மொழிபெயர்ப்பு (டெமோ):\n\n",
    note: "\n\n---\n*இது EduBridge AI ஆல் உருவாக்கப்பட்ட டெமோ மொழிபெயர்ப்பு.*",
  },
  kn: {
    greeting: "ಇದು ಡೆಮೋ ಅನುವಾದ.",
    prefix: "📝 ಕನ್ನಡ ಅನುವಾದ (ಡೆಮೋ):\n\n",
    note: "\n\n---\n*ಇದು EduBridge AI ಮೂಲಕ ಉತ್ಪತ್ತಿಯಾದ ಡೆಮೋ ಅನುವಾದ.*",
  },
  ml: {
    greeting: "ഇത് ഒരു ഡെമോ പരിഭാഷയാണ്.",
    prefix: "📝 മലയാളം പരിഭാഷ (ഡെമോ):\n\n",
    note: "\n\n---\n*EduBridge AI സൃഷ്ടിച്ച ഡെമോ പരിഭാഷ.*",
  },
  mr: {
    greeting: "हे एक डेमो भाषांतर आहे.",
    prefix: "📝 मराठी भाषांतर (डेमो):\n\n",
    note: "\n\n---\n*हे EduBridge AI ने तयार केलेले डेमो भाषांतर आहे.*",
  },
  bn: {
    greeting: "এটি একটি ডেমো অনুবাদ।",
    prefix: "📝 বাংলা অনুবাদ (ডেমো):\n\n",
    note: "\n\n---\n*এটি EduBridge AI দ্বারা তৈরি একটি ডেমো অনুবাদ।*",
  },
  es: {
    greeting: "Esta es una traducción de demostración.",
    prefix: "📝 Traducción al Español (Demo):\n\n",
    note: "\n\n---\n*Traducción de demostración generada por EduBridge AI.*",
  },
  fr: {
    greeting: "Ceci est une traduction de démonstration.",
    prefix: "📝 Traduction en Français (Démo):\n\n",
    note: "\n\n---\n*Traduction de démonstration générée par EduBridge AI.*",
  },
};

function getDemoTranslation(input: TranslateInput): string {
  const lang = input.targetLanguage;
  const langName = LANGUAGE_NAMES[lang] || lang;
  const demo = DEMO_TRANSLATIONS[lang];

  if (demo) {
    return `${demo.prefix}${input.text}${demo.note}`;
  }

  return `📝 ${langName} Translation (Demo):\n\n${input.text}\n\n---\n*Demo translation generated by EduBridge AI. Connect an OpenAI API key for real-time AI translations in 20+ languages.*`;
}

export async function translateText(input: TranslateInput): Promise<string> {
  // Return demo response when OpenAI is not configured
  if (DEMO_MODE) {
    return getDemoTranslation(input);
  }

  const cacheKey = generateCacheKey("translate", input as unknown as Record<string, unknown>);
  const cached = await getCachedResponse(cacheKey);
  if (cached) return cached;

  const targetLang = LANGUAGE_NAMES[input.targetLanguage] || input.targetLanguage;
  const sourceLang = LANGUAGE_NAMES[input.sourceLanguage || "en"] || "English";

  const systemPrompt = `You are a professional translator specializing in educational content.
Translate accurately while maintaining the educational context and meaning.
Preserve any technical terms with their translations in parentheses.
Only output the translated text, nothing else.`;

  const userPrompt = `Translate the following text from ${sourceLang} to ${targetLang}:

${input.text}`;

  const response = await chatCompletion(
    [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    { temperature: 0.3, maxTokens: 2000 }
  );

  await setCachedResponse(cacheKey, response, "translate");
  return response;
}

export function getSupportedLanguages() {
  return Object.entries(LANGUAGE_NAMES).map(([code, name]) => ({
    code,
    name,
  }));
}
